hidden: false
listed: true
textName: 
parents: []
blueprint: unit_tank_modular
livery: default
aiBehavior: Flanker
aiTargeting: sharpshooter
tags:
- branch_army
- branch_experimental
- branch_reserves
- branch_specops
- role_leader
- role_scout
- role_sharpshooter
- role_support
- type_tank_standard
subsystemTagPreferences: 
partTagPreferences:
  body:
  - tags:
      tank_medium: true
      tank_turret_aa: false
      tank_turret_adapter: false
      tank_elevated: false
  equipment_right:
  - tags:
      range_long: true
      tank_part: true
      tank_medium: true
      tank_light: false
      tank_heavy: false
parts: 
